services:
  neo4j:
    image: neo4j:5.23-community
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/docgentest
      - NEO4J_PLUGINS=["apoc","graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*
    ports:
      - "7474:7474"
      - "7687:7687"
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p docgentest 'RETURN 1'"]
      interval: 10s
      timeout: 10s
      retries: 10

  graph-builder:
    build: .
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=docgentest
    ports:
      - "8082:8082"
    volumes:
      - ../outputs/repo_output.json:/app/data/input.json:ro

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: