site_name: AIDocGen Documentation
site_description: AI documentation generation system

docs_dir: source
site_dir: build

theme:
  name: material
  features:
    - navigation.sections
    - search.highlight
    - content.code.copy
  palette:
    scheme: default
    primary: blue

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [..]
          options:
            docstring_style: numpy
            show_source: true
            show_signature_annotations: true
            members_order: source
            merge_init_into_class: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Home: index.md
  - How-to Guides: how-to-guides.md
  - Explanation: explanation.md
  - API Reference: reference.md
